"""agregar campo bonitaCaseId en la tabla emergencias

Revision ID: 474a2865356f
Revises: 6fb3eb6ff6f9
Create Date: 2026-09-24 22:39:28.074516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '474a2865356f'
down_revision: Union[str, Sequence[str], None] = '6fb3eb6ff6f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emergencias', sa.Column('bonitaCaseId', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emergencias', 'bonitaCaseId')
    # ### end Alembic commands ###
