"""añadiendo modelos de oferta y lote

Revision ID: 692e76ca72e1
Revises: 474a2865356f
Create Date: 2026-09-28 14:10:02.212803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '692e76ca72e1'
down_revision: Union[str, Sequence[str], None] = '474a2865356f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emergenciaId', sa.Integer(), nullable=False),
    sa.Column('tipoRecurso', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('cantidadCubierta', sa.Integer(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('fechaLimiteConvocatoria', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('fechaCreacion', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['emergenciaId'], ['emergencias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ofertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_lote', sa.Integer(), nullable=False),
    sa.Column('id_ong', sa.Integer(), nullable=False),
    sa.Column('cant_recurso', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_lote'], ['lotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ofertas')
    op.drop_table('lotes')
    # ### end Alembic commands ###
