"""crear tabla emergencias

Revision ID: 6fb3eb6ff6f9
Revises: 
Create Date: 2026-09-24 01:41:26.196400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6fb3eb6ff6f9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zonaAfectada', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('nivelGravedad', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('descripcionInicial', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('fechaCreacion', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emergencias')
    # ### end Alembic commands ###
