"""Agregar campo de usuario creador en emergencias

Revision ID: 80897f29c582
Revises: 692e76ca72e1
Create Date: 2026-09-30 17:57:40.342514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '80897f29c582'
down_revision: Union[str, Sequence[str], None] = '692e76ca72e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Existing emergencies have no recorded creator. Preserve them explicitly.
    op.add_column('emergencias', sa.Column('usuarioCreador', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False, server_default='sin_registro'))
    op.alter_column('emergencias', 'usuarioCreador', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emergencias', 'usuarioCreador')
    # ### end Alembic commands ###
